// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlsc8BHMdWQrYPPPtecSigi0wEMWsK-k',
    appId: '1:1072114785866:web:9ca6d6d16220c7904e90b3',
    messagingSenderId: '1072114785866',
    projectId: 'movigo-49b54',
    authDomain: 'movigo-49b54.firebaseapp.com',
    storageBucket: 'movigo-49b54.firebasestorage.app',
    measurementId: 'G-K1LP0NDSGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDud3kykTFILAe4dzQi3cVtGrpmRYTO0r4',
    appId: '1:1072114785866:android:ef60f06e984569294e90b3',
    messagingSenderId: '1072114785866',
    projectId: 'movigo-49b54',
    storageBucket: 'movigo-49b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cJlp57a0RwVhNONUtMB6JgQYfoTLrmk',
    appId: '1:1072114785866:ios:f8c231f02fdc4cd44e90b3',
    messagingSenderId: '1072114785866',
    projectId: 'movigo-49b54',
    storageBucket: 'movigo-49b54.firebasestorage.app',
    iosBundleId: 'com.example.movigoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_cJlp57a0RwVhNONUtMB6JgQYfoTLrmk',
    appId: '1:1072114785866:ios:f8c231f02fdc4cd44e90b3',
    messagingSenderId: '1072114785866',
    projectId: 'movigo-49b54',
    storageBucket: 'movigo-49b54.firebasestorage.app',
    iosBundleId: 'com.example.movigoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlsc8BHMdWQrYPPPtecSigi0wEMWsK-k',
    appId: '1:1072114785866:web:db783e53fc069b7c4e90b3',
    messagingSenderId: '1072114785866',
    projectId: 'movigo-49b54',
    authDomain: 'movigo-49b54.firebaseapp.com',
    storageBucket: 'movigo-49b54.firebasestorage.app',
    measurementId: 'G-PEMP37NXSB',
  );
}
